### ISSUE TITLE
[Enhancement] Fakeplayer / Forge Break events

### ISSUE THREAD

**Issue by spannerman79** [Eyeronic/DynamicTorches#2]
Hi,
I was looking at your mod and before I was going to try it out I had a quick search in your repo to see if you use a fake player or use forge break events when removing torches - which you don't.

This will cause issues for permission based systems (Like [MyTown2](https://minecraft.curseforge.com/projects/mytown2)).

May I suggest that you look at using either a fakeplayer or reflect the actual player when doing block break/place events.

**Comment by Eyeronic** [comment]
Hi and thanks for your feedback!

I am not entirely sure how to use a FakePlayer in my mod properly. After a quick search I tried out simply replacing the event.entityPlayer with a newly created FakePlayer (see [here](https://pastebin.com/4K3T3Np6)) but this way my onPlayerInteract in my main class method won't detect the player sneaking and therefore won't move the torch.
As mentioned in this mod's description I'm fairly new to Minecraft modding (and therefore Forge as well) so I expected using the standard BlockTorch functions would be enough. I will still dig around a bit more and read into Forge break events but some more advice from you where and how to utilize these things would be great ;)

**Comment by spannerman79** [comment]
I have zero coding experience but I can direct you to other mods that do use forge break events.

Digital Miner (Mekanism)
I am unsure under what code class it is but Mekanism github is https://github.com/aidancbrady/Mekanism/commit/77db81bcf0c0eaaa7f3757e7b1a610b804491253 (old commit)
The digital miner can be best explained via the wiki http://wiki.aidancbrady.com/wiki/Digital_Miner

Forestry:
The mod forestry uses the actual players uuid that placed the farm multiblock to do the forgebreak events (better and preferred)

https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/core/utils/PlayerUtil.java#L71-L74

I had a little comment discussion with @mezz via https://github.com/ForestryMC/ForestryMC/issues/902#issuecomment-159133687

Mekanism is MIT licensed, Forestry is GNU LESSER GENERAL PUBLIC LICENSE so I don't think either mod dev/s would mind you reading through their code to learn

**Comment by Eyeronic** [comment]
Ah, shame as this would have made things easier ^^
I'm gonna read into this and try to find out how to utilize it properly. Thanks again for your feedback! :)
